site_name: wknk-doc-js
site_author: wasknk    
repo_url: https://github.com/YourUsername/YourRepoName 

theme:
    name: readthedocs      
    highlightjs: true       

nav:
    - 首页: 'index.md'      
    - 脚本教程指南: 'guide.md' 
    - Docker Usage: 'docker.md'
    - Build tools of JS: 'build_tools.md'
    - vulnerability: 'vulnerability.md'
    - Eslint: 'eslint.md'
    - Nvm: 'nvm.md'
    - vite: 'vite.md'